### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by nmq443** [torcheeg/torcheeg#110]
**ImportError**: cannot import name 'hann' from 'scipy.signal' `(/home/quang/Study/Cognitive-Computing/cognitive-science-final-project/cognitive-science-env/lib/python3.10/site-packages/scipy/signal/__init__.py)`

**Reason**: scipy.signal version 1.13 no longer has `hann`, instead, `hann` is now inside the scipy.signal.windows module. I changed it inside 2 files: `torcheeg/transforms/numpy/band.py` and `torcheeg/transforms/numpy/band_pyeeg.py`. Hope anyone encounters this error can have a way to fix it.

**Comment by tczhangzhi** [comment]
Thank you for your report. We will address this issue in the next release.
For now, a quick fix is to install a lower version of scipy:
```
pip install scipy==1.10.1
```
