### ISSUE TITLE
running 'examples_mne_dataset.py' and went wrong

### ISSUE THREAD

**Issue by pentafingerLQCQ** [torcheeg/torcheeg#16]
I did not change anything about the code except add :`if __name__ == "__main__":`in front of `dataset = ......`

but I met the error as below:

`Can't pickle <function <lambda> at 0x00000230131CD3A0>: attribute lookup <lambda> on __main__ failed`
  `File "D:\torcheeg-main\examples\examples_mne_dataset.py", line 199, in <module>
    trainer.fit(train_loader, val_loader, num_epochs=50)`
`_pickle.PicklingError: Can't pickle <function <lambda> at 0x00000230131CD3A0>: attribute lookup <lambda> on __main__ failed`

asking for assistance

**Comment by tczhangzhi** [comment]
In some environments of Windows OS, you cannot use lambda functions for multi-process operations. So you may need to modify the codes like this:

```
# https://github.com/torcheeg/torcheeg/blob/main/examples/examples_mne_dataset.py

def minus_two(x):
    return x - 2

dataset = MNEDataset(epochs_list=epochs_list,
                     metadata_list=metadata_list,
                     chunk_size=160,
                     overlap=80,
                     io_path='./tmp_out/examples_mne_dataset/physionet',
                     offline_transform=transforms.Compose(
                         [transforms.MeanStdNormalize(),
                          transforms.To2d()]),
                     online_transform=transforms.ToTensor(),
                     label_transform=transforms.Compose([
                         transforms.Select('event'),
                         transforms.Lambda(minus_two) # see here
                     ]),
                     num_worker=2)
```
Or you can set num_worker to 0.
