### ISSUE TITLE
num_worker -1 should use all available workers

### ISSUE THREAD

**Issue by talhaanwarch** [torcheeg/torcheeg#19]
In most of python libraries, num_worker=-1 means to use all available workers. But in torcheeg package, num_worker=-1, means num_worker as 0.
So its better to use 

```
    if num_worker < 0:
        num_worker = os.cpu_count() + num_worker +1
```
Before
`    if num_worker > 1:`

in torcheeg/datasets/functional scripts.

**Comment by tczhangzhi** [comment]
We agree with you. If you don't mind, you can create a pull request.

**Comment by tczhangzhi** [comment]
Since the pull request has been merged, I will close this issue. If you have other questions, feel free to reopen it.
