### ISSUE TITLE
Color bar of topomap?

### ISSUE THREAD

**Issue by 1994cxy** [torcheeg/torcheeg#21]
How can I add a color bar in the plot_feature_topomap output?

**Comment by talhaanwarch** [comment]
It depends, if you want to have color bar with each topomap or one color bar for all topomaps.
Here is the modification for one color bar with each topomap.
This line needs to be modified
https://github.com/torcheeg/torcheeg/blob/95d7b577b57dbfcc51af01d605a4562d1f31a16a/torcheeg/utils/visualize.py#L71
to this 
```
for i, label in enumerate(plot_second_list):
    im, _ = mne.viz.plot_topomap(array[:, int(sampling_rate * label)],
                         info,
                         axes=axes[i],
                         show=False,
                         sphere=(0., 0., 0., 0.11))
    fig.colorbar(im, ax=axes[i])
img = plot2image(fig)
```

You will get output like this
![image](https://user-images.githubusercontent.com/37379131/234388538-626bc0cb-5681-411d-8dd2-7cf887703a98.png)

And if you want single color bar for all topoplots
Then modify it to this
```
ims = []
for i, label in enumerate(plot_second_list):
    im, _ = mne.viz.plot_topomap(array[:, int(sampling_rate * label)],
                         info,
                         axes=axes[i],
                         show=False,
                         sphere=(0., 0., 0., 0.11))
    ims.append(im)
    

    
vmin = min(im.get_clim()[0] for im in ims)
vmax = max(im.get_clim()[1] for im in ims)

v = [im.get_clim()[1] for im in ims] 

# Create a colorbar based on the minimum and maximum values
fig.colorbar(ims[v.index(max(v))], ax=axes, shrink=0.6, aspect=20, pad=0.03, ticks=np.linspace(vmin, vmax, 5))
    

img = plot2image(fig)
plt.show()    
```
This is the output produced
![image](https://user-images.githubusercontent.com/37379131/234391067-ccf3bc04-bb85-4e2b-bda9-ef96daee13bc.png)

**Comment by talhaanwarch** [comment]
This is for [plot_raw_topomap](https://torcheeg.readthedocs.io/en/latest/torcheeg.utils.html#plot-raw-topomap) but the code is same for [plot_feature_topomap](https://torcheeg.readthedocs.io/en/latest/torcheeg.utils.html#plot-feature-topomap)

**Comment by 1994cxy** [comment]
Very helpful!
