### ISSUE TITLE
Is there a guide to create location list and adjancency list

### ISSUE THREAD

**Issue by talhaanwarch** [torcheeg/torcheeg#24]

**Comment by tczhangzhi** [comment]
Please refer to the settings provided under the constant folder: https://github.com/torcheeg/torcheeg/blob/main/torcheeg/datasets/constants/emotion_recognition/amigos.py

Usually LOCATION_LIST comes from papers that analyze EEG signals based on CNN, for example:

Yang Y, Wu Q, Fu Y, et al. Continuous convolutional neural network with 3D input for EEG-based emotion recognition[C]//Neural Information Processing: 25th International Conference, ICONIP 2018, Siem Reap, Cambodia, December 13–16 , 2018, Proceedings, Part VII 25. Springer International Publishing, 2018: 433-443.

Zhang D, Yao L, Zhang X, et al. Cascade and parallel convolutional recurrent neural networks on EEG-based attention recognition for brain-computer interface[C]//Proceedings of the AAAI conference on artificial intelligence. 2018, 32(1).

ADJACENCY_LIST comes from papers that analyze EEG signals based on GNN, for example:

Song T, Liu S, Zheng W, et al. Instance-adaptive graph for EEG emotion recognition[C]//Proceedings of the AAAI Conference on Artificial Intelligence. 2020, 34(03): 2701-2708.

In fact, you can also define the position of the electrode in the grid or their nearest neighbors according to the position information provided by the EEG acquisition device. They usually follow the 10-20 or 10-05 system:

https://github.com/torcheeg/torcheeg/blob/main/torcheeg/datasets/constants/standard_1005.py

We conducted some experiments, and in fact, despite different mapping methods, they bring little difference in performance.

**Comment by tczhangzhi** [comment]
It looks like this issue has been resolved, so I'll close it. If you have other questions, feel free to reopen it.
