### ISSUE TITLE
Introduce different classification metrics in classification_trainer

### ISSUE THREAD

**Issue by talhaanwarch** [torcheeg/torcheeg#25]
Right now the [classification_trainer](https://github.com/torcheeg/torcheeg/blob/954404aa83b5fa03b85840d0bc97a3ecd340e389/torcheeg/trainers/classification_trainer.py#L120) only support accuracy, it would be better to add different classification metrics such as precision, recall and F1-score

**Comment by tczhangzhi** [comment]
Thanks for your contribution, I've closed the issue since this pull request has been merged. If you have other questions about this branch, please feel free to reopen it.
