### ISSUE TITLE
About SEED Dataset's 'info.csv' didn't find.

### ISSUE THREAD

**Issue by monsteryi0314** [torcheeg/torcheeg#35]
Can't find 'info.csv' this file in SEED Dataset. How can I make it? or any ways?
FileNotFoundError: [Errno 2] No such file or directory: './temp_out/seed/info.csv'

**Comment by tczhangzhi** [comment]
Sorry for the late reply, you can refer to #2. It's essentially multiprocessing on some systems not behaving as expected, and therefore not generating files. On existing versions, you may consider setting `num_worker=0`.

We recently refactored TorchEEG to make multiprocessing run efficiently on windows, mac and colab. You can install the development version and enjoy efficient multiprocessing without bugs, on any system:
```
!pip install git+https://github.com/tczhangzhi/torcheeg.git
```
