### ISSUE TITLE
Loading SEED dataset

### ISSUE THREAD

**Issue by edugm94** [torcheeg/torcheeg#66]
Hello,

I found this toolkit, which I find fascinating! I am trying to learn it, but I am having some problems to load the datasets. 
I am using Class `SEEDDataset` to load the dataset. However, it seems nothing is loaded. I attach a figure of the compiler: 
![Screenshot from 2023-11-09 08-54-33](https://github.com/torcheeg/torcheeg/assets/45097147/febd45cd-d3b3-4af1-acc3-388f51022859)

If someone could help me to understand what I am doing wrong, I would really appreciate it! 

Thanks in advance :)

**Comment by tczhangzhi** [comment]
Your code looks fine. You may need to wait for the program to complete.

Providing more information will help locate your problem, or you can run this mini-case example showing how to load the SEED dataset:

https://colab.research.google.com/drive/1POEdPRKt3g2Nc4iihTKc_gKRHGSMPwjJ?usp=sharing

**Comment by edugm94** [comment]
Hi, 

Thanks for fast response! 
I tried to do `print(dataset)` as it is done in the tutorial, and I got the error: `{TypeError}object of type 'NoneType' has no len()`

I understood that `root_path` should be the path to the files. In the case of SEED: .mat, labels.mat and readme.txt files. 
I have the latest version of torcheeg. 

Thanks so much for any insight!

**Comment by tczhangzhi** [comment]
You may want to try the following code. I suspect there are two issues with the snippet of code you've provided:

1. 'io_path' should be a directory for caching processed results. The program will create this by default, so you just need to specify a directory that doesn't currently exist.
2. There seems to be an error with 'root_path'. It appears to be missing a '/' symbol.

```
dataset = SEEDDataset(io_path=f'./seed',
                      root_path=f'{path}/Preprocessed_EEG',
                      offline_transform=transforms.Compose([
                          transforms.BandDifferentialEntropy(sampling_rate=200),
                          transforms.ToGrid(SEED_CHANNEL_LOCATION_DICT)
                      ]),
                      online_transform=transforms.ToTensor(),
                      label_transform=transforms.Compose([
                          transforms.Select('emotion'),
                          transforms.Lambda(lambda x: x + 1)
                      ]),
                      chunk_size=200)
```

**Comment by edugm94** [comment]
Hi! 

I had to remove the `chunk_size` argument, but now it worked :) 

Thanks so much!!!

**Comment by tczhangzhi** [comment]
Since there hasn't been any new reply for a long time, it seems like the issue has been resolved. I am going to close this issue, but if you need further help, please feel free to re-open it.
