### ISSUE TITLE
Error into BandDifferentialEntropy implementation?

### ISSUE THREAD

**Issue by Nhix00** [torcheeg/torcheeg#71]
I'm using torch EEG for my studies and i found that the differential entropy is calculated using this formula in BandDifferentialEntropy class:

```python
def opt(self, eeg: np.ndarray, **kwargs) -> np.ndarray:
        return 1 / 2 * np.log2(2 * np.pi * np.e * np.std(eeg))
``` 

Lokin into different papers and into the cited onces in the method, i discovered that the differential entropy feature is computed with variance, cause the sigma in the formula should be elevated at the power of 2, am I missing something or I'm right?

I think the correct computation shoul be:

```python
def opt(self, eeg: np.ndarray, **kwargs) -> np.ndarray:
        return 1 / 2 * np.log2(2 * np.pi * np.e * np.var(eeg))
``` 

or:

```python
def opt(self, eeg: np.ndarray, **kwargs) -> np.ndarray:
        return 1 / 2 * np.log2(2 * np.pi * np.e * (np.std(eeg))**2)
```

**Comment by tczhangzhi** [comment]
We've reviewed the paper and the project, and your understanding is correct. This is indeed a serious bug. Thank you very much. If you're willing, you're welcome to create a pull request.

We will immediately investigate the cause of this error to prevent similar issues. I suspect it might have aligned with an incorrect implementation during the refactoring process.

**Comment by tczhangzhi** [comment]
#72
