### ISSUE TITLE
import ClassifierTrainer出现问题

### ISSUE THREAD

**Issue by 2638289491** [torcheeg/torcheeg#75]
运行实例代码中，出现ImportError: cannot import name 'ClassifierTrainer' from 'torcheeg.trainers' (D:\anaconda\lib\site-packages\torcheeg\trainers\__init__.py)错误，已检查anaconda文件夹中，两个函数都没有问题

**Comment by tczhangzhi** [comment]
Could you check the version of torcheeg in the conda environment you are using? The version 1.1.0 of torcheeg works well.

Please check according to the following example:
https://colab.research.google.com/drive/1rdrwENcI0KQJZIuAJ6xlMZbyTvxfSwgd?usp=sharing

**Comment by 2638289491** [comment]
thank you，I can run this code successfully，but no results atfer running.
![image](https://github.com/torcheeg/torcheeg/assets/88307299/be31ddb4-4d85-46fc-8d71-21785c681e0c)

**Comment by tczhangzhi** [comment]
It works well in all tests. Can you print the length of the dataset, or examine the loop of k_fold.split?

One approach is to clear the generated IO and rerun the program.

**Comment by tczhangzhi** [comment]
Please also refer to this public kernel on Kaggle:

https://www.kaggle.com/code/szuzhangzhi/eeg-based-emotion-recognition/

**Comment by tczhangzhi** [comment]
Since there hasn't been any new reply for a long time, it seems like the issue has been resolved. I am going to close this issue, but if you need further help, please feel free to re-open it.
