### ISSUE TITLE
Custom Dataset problem

### ISSUE THREAD

**Issue by TomasSand** [torcheeg/torcheeg#76]
Hello, i'm try to use module relative to NumpyDataset, but don't find. How can i import this Module?
Thanks in advantage

**Comment by tczhangzhi** [comment]
In versions after torcheeg==1.1.0, NumpyDataset is no longer supported.

It is recommended to use [FolderDataset](https://torcheeg.readthedocs.io/en/latest/generated/torcheeg.datasets.FolderDataset.html#torcheeg.datasets.FolderDataset) or [CSVFolderDataset](https://torcheeg.readthedocs.io/en/latest/generated/torcheeg.datasets.CSVFolderDataset.html#torcheeg.datasets.CSVFolderDataset).
